### ISSUE TITLE
Alfred theme?

### ISSUE THREAD

**Issue by firstchair** [uetchy/alfred-workflow-ghq#1]
Hi, Not really an issue, but im curious what alfred theme is used in the screenshots.
Been looking for it but cant find it... Thanks.

**Comment by uetchy** [comment]
I made it myself. Download it here if you are interested; some accent colours have changed since then though.

[Catalina Dark.zip](https://github.com/uetchy/alfred-workflow-ghq/files/5230141/Catalina.Dark.zip)
